hash-format = "sha256"

[[files]]
file = "config/customsplashscreen.json5"
hash = "49ffb0b1397a888d766d04581e51e576189446b053e099b8aa8a984fbb4e262b"

[[files]]
file = "config/customsplashscreen/happypack.png"
hash = "6534415bce63ebc1348a0459c8afc24a00f5a1a61ad3abb4f27a83a1c4d730d2"

[[files]]
file = "config/customsplashscreen/hp_background.jpg"
hash = "66675bf91f4e848eb72d993552eb9dd8e10df5541c2ee4b76d2a8104e0976882"

[[files]]
file = "config/customstars.json"
hash = "e370868cdd62cfce31b90da3a1fbc51e64540787862a1de8bdb622277294fe57"

[[files]]
file = "config/easierchests.json"
hash = "d99aa332b5eebf80bee14782219ebceaa51e9bf9c44f390ed8418589f1c7b40a"

[[files]]
file = "config/puzzle/blocks.json"
hash = "30459cfdf792df3566342d95b1990136b6acf88a3903d044e4c1c0f1bbdcc383"

[[files]]
file = "config/splasher.toml"
hash = "7762ee36c2fc4cc86cc1b7b73878b89f3fbb877a690dbc8f0d6d984ecde9e994"

[[files]]
file = "config/splasher/en_us.txt"
hash = "fdb6795907fef54a8c26fbf866da9b44e7b31e639292e53502093acdf8c34344"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "c46783fcb333e7989d84c611de7e8fec95ef0e15d8a1db762cdaff8db53e4445"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "4fc60bed2e227016e7027f79a4ee1ca4c1825d5698d2afbedfe63fe5f24639d0"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e41f2ba64cc3364217a3f4f10ce034ea24b0a4795847b0013e64370e43a87307"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "240ecedc7fb969d0206e9de97a62125e6efb0bc388fab3d83c4d2774f610c353"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "d1b771355272dd080b00c13b035a972a8fec5234033c0166252db90b8bfee0ac"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "cc244b0378f73dd31201cb7e3bbb457c90ff32bd71415a39b9991418ac4390d7"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "b21f08b384c084e21c07cd2cd4960b498d39b65038fb0ee16793e3662120be58"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b2103de7f3d13a7b7868890afd358e51f93bea4914e226fc0fbe53bdb84ff7e8"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "9d9d089ba6f7f6cdd1718434991df57e999916fbd0b807b105670a7f733469ee"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "f6920294f3a0a0a22053e8cdd2d5d73d3d3063200f701ca55936daae73152e44"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "786673d99fd07e777cc2819514c61bb228930bd245e14e2f985423c77a27ac92"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fa8be992c1e3efbd030ef6a84409b766a936deb3fc3d06b657f8e468745044f0"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44ce91936136fb30c08b2f062e6d92493f1f2cc5a526a8039b54d1ae3f61279c"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "b548e077d7f9c77a68dca16a40efdfe8e3c9e7b28f3162a91f4b0b53dab12336"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "14a1c6668f6be427e0bf9a1b9171282334b8e6f557b13d7afac73cfa857dfe46"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "e4d0dbbe4dd9b0d81ded34fc361c5174a151fa6cc2d8d89e3745c44188a519f6"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "89a3b35c2465973fad545085c89d02c6d9915b933bce25602431f30ef282d027"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "ad723fbfa74029c4487bf2b7fe12232f89e36044a01ecbbcd4fcda45e9c34383"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "d18162d6e21a10e142b31370cddd2eb234a3a04fe5e05c4627584954bbfc9dab"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "9f75561621ce420c3aeedfd4260cf0ec504c3cea267a1623f40c142f605a855a"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "9df913674f1ca1b37098587387f62e69df86f3abe50d9c506cf6cb518a6e1228"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9cb7b03b45eb9eede9748fd6dfb4de9396378ce7883da6d0da657675c7aa060d"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "e187eeabc31097e22705f22658a6dc0fb094b17a51075ebb68f479f04a44d60c"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "6b87238f283f3773bcc6df72196df3e62c1a073c8f397f37e32fa41f8f573193"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "8ced9b74b91b485f78d0b56fa54bc352dd71db8e52a5e234cf6872cdf9e71aad"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0e0970dafc9680fba4dc73434baad6aa7dee91ab4994f33b2493ea5b4c59931d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5e28a5bc87a799a03a72e641c1118b7d9ba955dceb70e2427fe0c2b15ed5186e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "fbb68e5991ad23a75679bc7deae303166393ec3108e40d133054a4cc8914e5fd"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "50ca0e5deda0fb77d4f230e0f61692432968c1ae2a8ee3188ba9a9c475921fc0"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "110de4d87ccb3fe2799285e17b9fa723ecace1c8f16ee762461b03b906536b9b"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "3753e418cf9a1feb5241ebaf97f8f449ec8a255ee48a493b2f4db305951d7d86"
metafile = true

[[files]]
file = "resourcepacks/HappyPack/assets/minecraft/texts/splashes.txt"
hash = "710f5de9aa106d37d9de8704cabf288420b2f8330fa35a129125f9a73c8adf39"

[[files]]
file = "resourcepacks/HappyPack/assets/minecraft/textures/gui/title/background/panorama_overlay.png"
hash = "82caa63594a9c3d8eb8cb0134d3c5a25ea9885bf82c02eca1e0e3a8e0098049c"

[[files]]
file = "resourcepacks/HappyPack/assets/minecraft/textures/gui/title/minecraft.png"
hash = "9f6da76c54b1cd7e722cec10093de64819e4f12fd476f7769e323d09635a50da"

[[files]]
file = "resourcepacks/HappyPack/pack.mcmeta"
hash = "ecaea70a08110adb0c25c4d6f95852edea14323bb3a59011099cb6fb38188b21"

[[files]]
file = "servers.dat"
hash = "3a268afd53ec4e640ce2f9a0da3eb0ea67b81a188253dd703a8cc50a2926a624"

[[files]]
file = "shaderpacks/MakeUp-UltraFast-8.7a.zip.txt"
hash = "199b700df56fc8fc854f7686a63804cac02d2b67182e9b09c38a657b956e212c"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "dab75b3a7685b899a24a0a3ef1dda7b77047997f8e2a627ac126cfb820fa761d"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "c07e5f304bec5474efba2a85e919e4bbb2678bdf1d3b972ccb343e6800326945"
metafile = true
