name = "Happy Pack"
author = "HappyRads"
version = "1.12710.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aef13cedefba861f95552e5c7903f0eba4c8da912bbe22766377ea0f89ed4bb"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
