name = "Happy Pack"
author = "HappyRads"
version = "1.12710.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58c227c7a9affb833d6b67f4f54026834fb8ebf2968876c189704375833d355f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
